import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../memorization_calc.dart' show MemorizationDirection;

/// Types of rows in the mushaf layout asset.
enum MushafLineType {
  /// A regular text line of the mushaf.
  text,

  /// The ornamented surah-name banner line (mid-page surah start).
  surahHeader,

  /// The basmala line that follows a surah header.
  basmala,

  /// A blank row (the printed mushaf always has 15 rows per page).
  blank,
}

/// One row of the Madani mushaf page (type, exact text, verse coverage).
@immutable
class MushafLine {
  const MushafLine({
    required this.type,
    required this.text,
    this.from,
    this.to,
    this.ayahRefs = const [],
  });

  final MushafLineType type;

  /// Exact Uthmani text of the row, including Arabic-Indic ayah numbers.
  final String text;

  /// First ayah covered by a text line, "s:a".
  final String? from;

  /// Last ayah covered by a text line, "s:a".
  final String? to;

  /// Every ayah ("s:a") fully or partially present on this line, in order.
  final List<String> ayahRefs;

  bool get isText => type == MushafLineType.text;
}

/// One contiguous run of text lines on a page that belongs to a review
/// window (e.g. "the last 3 days of memorized lines").
@immutable
class ReviewSegment {
  const ReviewSegment({
    required this.page,
    required this.startLine,
    required this.lineCount,
  });

  /// Page number 1..604.
  final int page;

  /// 0-based index into the page's [MushafPage.textLines] where the run starts.
  final int startLine;

  /// Number of text lines on this page included in the window.
  final int lineCount;

  @override
  bool operator ==(Object other) =>
      other is ReviewSegment &&
      other.page == page &&
      other.startLine == startLine &&
      other.lineCount == lineCount;

  @override
  int get hashCode => Object.hash(page, startLine, lineCount);
}

/// One page of the mushaf with its juz and header surah.
@immutable
class MushafPage {
  const MushafPage({
    required this.page,
    required this.juz,
    required this.surah,
    required this.lines,
  });

  /// Page number 1..604.
  final int page;

  /// Juz number 1..30 that this page belongs to.
  final int juz;

  /// Surah shown in the page header (the first surah on the page).
  final int surah;

  /// The 15 rows of the page, in order.
  final List<MushafLine> lines;

  /// Only the real text lines (excludes header/basmala/blank rows).
  List<MushafLine> get textLines => [
    for (final l in lines)
      if (l.isText) l,
  ];

  /// Today's assignment: [lineCount] text lines, taken from the start when
  /// memorizing 1 → 604 and from the end when memorizing 604 → 1.
  List<MushafLine> todayLines({
    required int lineCount,
    required MemorizationDirection direction,
  }) {
    final texts = textLines;
    if (texts.isEmpty || lineCount <= 0) return const [];
    final n = lineCount > texts.length ? texts.length : lineCount;
    return direction == MemorizationDirection.backward
        ? texts.sublist(texts.length - n)
        : texts.take(n).toList();
  }
}

/// Surah metadata used by the page header and mid-page banners.
@immutable
class SurahMeta {
  const SurahMeta({
    required this.number,
    required this.arabicName,
    required this.arabicLong,
    required this.transliteration,
    required this.ayahCount,
  });

  final int number;

  /// Short Arabic name, e.g. "الفاتحة".
  final String arabicName;

  /// Long form used on mushaf banners, e.g. "سُورَةُ ٱلْفَاتِحَةِ".
  final String arabicLong;

  final String transliteration;
  final int ayahCount;
}

/// Bundled line-level Madani mushaf layout (offline-first).
///
/// Loaded from assets/mushaf_lines.json, generated by
/// tool/generate_mushaf_lines.py from the zonetecde/mushaf-layout dataset
/// (Hafs 'an 'Asim, 604 pages x 15 lines).
@immutable
class MushafData {
  const MushafData({required this.surahs, required this.pages});

  /// Total pages in the standard Madani mushaf.
  static const int totalPages = 604;

  final List<SurahMeta> surahs;
  final List<MushafPage> pages;

  /// Parses the bundled JSON (used by [load] and by tests with fixtures).
  factory MushafData.fromJson(Map<String, dynamic> json) {
    final surahs = [
      for (final s in (json['surahs'] as List))
        SurahMeta(
          number: (s as Map<String, dynamic>)['s'] as int,
          arabicName: s['n'] as String,
          arabicLong: s['l'] as String,
          transliteration: s['t'] as String,
          ayahCount: s['c'] as int,
        ),
    ];
    final pages = [
      for (final p in (json['pages'] as List))
        MushafPage(
          page: (p as Map<String, dynamic>)['p'] as int,
          juz: p['j'] as int,
          surah: p['s'] as int,
          lines: [
            for (final l in (p['l'] as List))
              MushafLine(
                type: switch (l['t'] as int) {
                  1 => MushafLineType.surahHeader,
                  2 => MushafLineType.basmala,
                  3 => MushafLineType.blank,
                  _ => MushafLineType.text,
                },
                text: l['x'] as String,
                from: l['f'] as String?,
                to: l['g'] as String?,
                ayahRefs: [
                  for (final a in (l['a'] as List? ?? const [])) a as String,
                ],
              ),
          ],
        ),
    ];
    return MushafData(surahs: surahs, pages: pages);
  }

  /// Loads the bundled asset. Throws if the asset is missing or corrupt.
  static Future<MushafData> load() async {
    final raw = await rootBundle.loadString('assets/mushaf_lines.json');
    return MushafData.fromJson(jsonDecode(raw) as Map<String, dynamic>);
  }

  /// Page [page] (1..604).
  MushafPage page(int page) {
    if (page < 1 || page > totalPages) {
      throw RangeError.range(page, 1, totalPages, 'page');
    }
    return pages[page - 1];
  }

  /// Metadata for [surah] (1..114).
  SurahMeta surahMeta(int surah) => surahs[surah - 1];

  /// The nightly review window: the [reviewDays] most recent study days of
  /// memorized lines (each day = [linesPerDay] text lines), ending at today's
  /// assignment on [page]. Returns the runs oldest-first so a review session
  /// plays from the earliest content to today.
  ///
  /// Forward direction (page 1 → 604) walks back to earlier pages; backward
  /// direction (604 → 1) walks to later pages. Clamps when the mushaf runs
  /// out (e.g. reviewing from page 1) and returns an empty list for
  /// [reviewDays] <= 0 or a non-positive [linesPerDay].
  List<ReviewSegment> reviewSegments({
    required int currentPage,
    required double linesPerDay,
    required MemorizationDirection direction,
    required int reviewDays,
  }) {
    if (reviewDays <= 0 || linesPerDay <= 0) return const [];
    final todayCount = linesPerDay
        .round()
        .clamp(0, page(currentPage).textLines.length)
        .toInt();
    final total = (linesPerDay * reviewDays).round();
    final segments = <ReviewSegment>[];
    var remaining = total;
    var cur = currentPage;

    if (direction == MemorizationDirection.backward) {
      // Today is the last lines of the page; earlier days lie on later pages.
      final start = page(currentPage).textLines.length - todayCount;
      final take = todayCount < remaining ? todayCount : remaining;
      if (take > 0) {
        segments.add(ReviewSegment(page: cur, startLine: start, lineCount: take));
        remaining -= take;
      }
      cur = currentPage + 1;
      while (remaining > 0 && cur <= pages.length) {
        final c = page(cur).textLines.length;
        final t = c < remaining ? c : remaining;
        segments.add(ReviewSegment(page: cur, startLine: 0, lineCount: t));
        remaining -= t;
        cur++;
      }
      // segments are newest-first (today .. oldest); reverse to play oldest first.
      return segments.reversed.toList();
    }

    // Forward: today is the first lines of the page; earlier days lie on the
    // tail of the previous pages. Insert older pages at the front so the
    // result is oldest-first.
    final take = todayCount < remaining ? todayCount : remaining;
    if (take > 0) {
      segments.add(ReviewSegment(page: cur, startLine: 0, lineCount: take));
      remaining -= take;
    }
    cur = currentPage - 1;
    while (remaining > 0 && cur >= 1) {
      final c = page(cur).textLines.length;
      final t = c < remaining ? c : remaining;
      segments.insert(0, ReviewSegment(page: cur, startLine: c - t, lineCount: t));
      remaining -= t;
      cur--;
    }
    return segments;
  }
}

/// Formats [n] with Arabic-Indic digits (0→٠ … 9→٩), as used on the mushaf
/// page headers for page and juz numbers.
String toArabicIndic(int n) {
  const digits = '٠١٢٣٤٥٦٧٨٩';
  return n.toString().split('').map((c) => digits[c.codeUnitAt(0) - 48]).join();
}
