import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

/// Bundled English translation of the Quran (Saheeh International),
/// offline-first like the rest of the app.
///
/// Loaded from assets/quran_translation.json, generated by
/// tool/generate_quran_translation.dart from alquran.cloud's en.sahih
/// edition (attribution in the asset's meta field). The array is in the
/// same global ayah order as [QuranText]'s text (0 = 1:1, 6235 = 114:6).
@immutable
class QuranTranslation {
  const QuranTranslation._({required this._translations, required this.edition});

  /// Total ayahs in the Quran.
  static const int totalAyahs = 6236;

  /// Edition identifier, e.g. "en.sahih".
  final String edition;

  final List<String> _translations;

  /// Parses the bundled JSON (used by [load] and by tests with fixtures).
  factory QuranTranslation.fromJson(Map<String, dynamic> json) {
    final translations = (json['translation'] as List).cast<String>();
    if (translations.length != totalAyahs) {
      throw StateError(
        'expected $totalAyahs translations, got ${translations.length}',
      );
    }
    final meta = (json['meta'] as Map<String, dynamic>?) ?? const {};
    return QuranTranslation._(
      translations: translations,
      edition: meta['edition'] as String? ?? 'unknown',
    );
  }

  /// Loads the bundled asset. Throws if the asset is missing or corrupt.
  static Future<QuranTranslation> load() async {
    final raw = await rootBundle.loadString('assets/quran_translation.json');
    return QuranTranslation.fromJson(jsonDecode(raw) as Map<String, dynamic>);
  }

  /// English meaning of the ayah at global index [index]
  /// (0-based; 0 = 1:1, 6235 = 114:6), the same order as [QuranText]'s text.
  String translationAt(int index) {
    if (index < 0 || index >= totalAyahs) {
      throw RangeError.range(index, 0, totalAyahs - 1, 'index');
    }
    return _translations[index];
  }
}
