import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

/// One ayah of the Quran with its mushaf position and Uthmani text.
@immutable
class Ayah {
  const Ayah({required this.surah, required this.ayah, required this.text});

  /// Surah number, 1..114.
  final int surah;

  /// Ayah number within [surah], 1..286.
  final int ayah;

  /// Uthmani Arabic text of the ayah.
  final String text;

  /// Compact reference like "2:255".
  String get reference => '$surah:$ayah';
}

/// Metadata for one surah (chapter).
@immutable
class SurahInfo {
  const SurahInfo({
    required this.number,
    required this.ayahCount,
    required this.arabicName,
    required this.transliteration,
  });

  final int number;
  final int ayahCount;
  final String arabicName;
  final String transliteration;
}

/// Bundled Quran text + Madani page layout (offline-first).
///
/// Loaded from assets/quran_data.json, generated by
/// tool/generate_quran_data.dart from fawazahmed0/quran-api Uthmani text and
/// Tanzil Project page metadata (attribution in the asset's meta field).
@immutable
class QuranText {
  QuranText._({
    required this._text,
    required this._pages,
    required List<SurahInfo> surahs,
  }) : _surahs = surahs {
    var offset = 0;
    for (final s in surahs) {
      _surahStart.add(offset);
      offset += s.ayahCount;
    }
  }

  /// Total pages in the standard Madani mushaf.
  static const int totalPages = 604;

  final List<String> _text;
  final List<List<int>> _pages;
  final List<SurahInfo> _surahs;
  final List<int> _surahStart = [];

  /// Parses the bundled JSON (used by [load] and by tests with fixtures).
  factory QuranText.fromJson(Map<String, dynamic> json) {
    final text = (json['text'] as List).cast<String>();
    final pages = (json['pages'] as List)
        .map((page) => (page as List).cast<int>())
        .toList();
    final surahs = [
      for (final s in (json['surahs'] as List))
        SurahInfo(
          number: (s as Map<String, dynamic>)['s'] as int,
          ayahCount: s['c'] as int,
          arabicName: s['n'] as String,
          transliteration: s['t'] as String,
        ),
    ];
    return QuranText._(text: text, pages: pages, surahs: surahs);
  }

  /// Loads the bundled asset. Throws if the asset is missing or corrupt.
  static Future<QuranText> load() async {
    final raw = await rootBundle.loadString('assets/quran_data.json');
    return QuranText.fromJson(jsonDecode(raw) as Map<String, dynamic>);
  }

  /// Ayahs that appear on [page] (1..604), in reading order.
  List<Ayah> pageAyahs(int page) {
    _checkPage(page);
    return [for (final i in _pages[page - 1]) ayahAt(i)];
  }

  /// Number of ayahs on [page] (1..604).
  int ayahCountOnPage(int page) {
    _checkPage(page);
    return _pages[page - 1].length;
  }

  /// Metadata for [surah] (1..114).
  SurahInfo surahInfo(int surah) => _surahs[surah - 1];

  /// The ayah at global index [index] (0-based; 0 = 1:1, 6235 = 114:6).
  Ayah ayahAt(int index) {
    var lo = 0;
    var hi = _surahs.length - 1;
    while (lo < hi) {
      final mid = (lo + hi + 1) >> 1;
      if (_surahStart[mid] <= index) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }
    final surah = lo + 1;
    return Ayah(
      surah: surah,
      ayah: index - _surahStart[lo] + 1,
      text: _text[index],
    );
  }

  void _checkPage(int page) {
    if (page < 1 || page > totalPages) {
      throw RangeError.range(page, 1, totalPages, 'page');
    }
  }
}

/// Approximates today's memorization assignment as ayahs on the current page:
/// the fraction of the page covered by [linesPerDay] of [linesPerPage] lines,
/// converted to whole ayahs (ceil), clamped to the page.
///
/// True mushaf line boundaries need a dedicated line-layout dataset; this is
/// the ayah-level approximation until then.
int todayAyahCount({
  required int ayahsOnPage,
  required double linesPerDay,
  int linesPerPage = 15,
}) {
  if (ayahsOnPage <= 0 || linesPerDay <= 0) return 0;
  final fraction = (linesPerDay / linesPerPage).clamp(0.0, 1.0);
  return (fraction * ayahsOnPage).ceil().clamp(0, ayahsOnPage).toInt();
}
